import Head from 'next/head'
import Map from 'react-map-gl';

export default function Home() {
  return (
    <>
      <Head>
        <title>Map App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Map
            mapboxAccessToken={process.env.NEXT_PUBLIC_MAPBOX_API_TOKEN}
            initialViewState={{
              longitude: -122.4,
              latitude: 37.8,
              zoom: 14
            }}
          />
        </div>
      </main>
    </>
  )
}
